Create Database Connection
xyluz/business-canvas pull request #18
Opened 2022-11-28 13:14 UTC by Abiodun-Shittu

## Create Database Connection
- Using MongoDB

2022-12-01 14:51 UTC, xyluz requested changes

2022-12-01 14:51 UTC, xyluz commented on database/db.js
> +		await mongoose.connect(process.env.MONGO_URL)
Please add .env.example

2022-12-01 16:41 UTC, Abiodun-Shittu commented on database/db.js
> +		await mongoose.connect(process.env.MONGO_URL)
okay, will do that now

2022-12-01 16:43 UTC, Abiodun-Shittu commented on database/db.js
> +		await mongoose.connect(process.env.MONGO_URL)
Resolved

2022-12-02 14:08 UTC, xyluz commented
Please resolve conflicts

2022-12-02 16:12 UTC, Abiodun-Shittu commented
> Please resolve conflicts

conflict resolved

2022-12-05 14:36 UTC, merged